name: build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Client
        working-directory:./client
        run: npm install

      - name: Build Client
        working-directory:./client
        run: npm run build
        env:
          VITE_ONLINE_API_URL: https://your-backend.onrender.com
          VITE_LOCAL_API_URL: http://192.168.1.100:5000

      - name: Install Server
        working-directory:./server
        run: npm install
