name: KSS Connect Build Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Client
        working-directory:./client
        run: |
          npm install
          npm run build

      - name: Check Server
        working-directory:./server
        run: npm install
